'use client';
// react
import React, { useEffect, useState } from 'react';

// antd
import Layouts from '../components/Layouts';
import { AuthProvider } from '../contexts/AuthenticationContext';

// styles
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='min-h-screen'>
				{' '}
				<AuthProvider>
					<Layouts>{children}</Layouts>
				</AuthProvider>
			</body>
		</html>
	);
}
